"use strict";


export function check_animation_time(quCreative_main) {
  if(window.qucreative_view_animation_duration){
    quCreative_main.view_animation_duration = window.qucreative_view_animation_duration * 1000;
  }
}

/**
 * Initialize the responsive menu (generated by PHP)
 * @param quCreative_main
 * @param _body
 */
export function quBuildResponsiveMenu(quCreative_main, _body) {

  const qcm = quCreative_main;

  // Find the responsive menu container (generated by PHP)
  if (qcm._theContent && qcm._theContent.length) {
    qcm._navCon_520 = qcm._theContent
      .parent()
      .children(".qucreative--520-nav-con")
      .eq(0);
  }

  // Exit if responsive menu not found
  if (!qcm._navCon_520 || !qcm._navCon_520.length) {
    return;
  }

  // Find the menu target element
  let _cac = qcm._navCon_520
    .find(".dzs-select-wrapper select")
    .eq(0);

  // Check if using custom responsive menu
  if (qcm._navCon_520.children(".custom-responsive-menu").length > 0) {
    qcm.custom_responsive_menu = true;
    _cac = qcm._navCon_520
      .children(".custom-responsive-menu")
      .find(".custom-menu")
      .eq(0);
  }

  // Clear the menu content (will be populated by JavaScript menu builder)
  // _cac.html("");
}


