window.dzsprx_self_options={};
(function(c){c.fn.dzsparallaxer=function(a){if("undefined"==typeof a&&"undefined"!=typeof c(this).attr("data-options")&&""!=c(this).attr("data-options")){var h=c(this).attr("data-options");eval("window.dzsprx_self_options = "+h);a=c.extend({},window.dzsprx_self_options);window.dzsprx_self_options=c.extend({},{})}a=c.extend({settings_mode:"scroll",mode_scroll:"normal",easing:"easeIn",animation_duration:"20",direction:"normal",js_breakout:"off",breakout_fix:"off",is_fullscreen:"off",cthis_height_is_window_height:"off",
    settings_movexaftermouse:"off",init_delay:"0",init_functional_delay:"0",settings_substract_from_th:0,init_functional_remove_delay_on_scroll:"off",settings_makeFunctional:!1,settings_scrollTop_is_another_element_top:null,settings_clip_height_is_window_height:!1,settings_listen_to_object_scroll_top:null},a);Math.easeIn=function(a,c,h,r){return-h*(a/=r)*(a-2)+c};Math.easeOutQuad=function(a,c,h,r){a/=r;return-h*a*(a-2)+c};Math.easeInOutSine=function(a,c,h,r){return-h/2*(Math.cos(Math.PI*a/r)-1)+c};this.each(function(){function h(){if(1==
    a.settings_makeFunctional){var m=!1,e=document.URL,g=e.indexOf("://")+3,k=e.indexOf("/",g);e=e.substring(g,k);-1<e.indexOf("l")&&-1<e.indexOf("c")&&-1<e.indexOf("o")&&-1<e.indexOf("l")&&-1<e.indexOf("a")&&-1<e.indexOf("h")&&(m=!0);-1<e.indexOf("d")&&-1<e.indexOf("i")&&-1<e.indexOf("g")&&-1<e.indexOf("d")&&-1<e.indexOf("z")&&-1<e.indexOf("s")&&(m=!0);-1<e.indexOf("o")&&-1<e.indexOf("z")&&-1<e.indexOf("e")&&-1<e.indexOf("h")&&-1<e.indexOf("t")&&(m=!0);-1<e.indexOf("e")&&-1<e.indexOf("v")&&-1<e.indexOf("n")&&
-1<e.indexOf("a")&&-1<e.indexOf("t")&&(m=!0);if(0==m)return}a.settings_scrollTop_is_another_element_top&&(t=a.settings_scrollTop_is_another_element_top);l=b.find(".dzsparallaxer--target").eq(0);0<b.find(".dzsparallaxer--blackoverlay").length&&(F=b.find(".dzsparallaxer--blackoverlay").eq(0));0<b.find(".dzsparallaxer--fadeouttarget").length&&(T=b.find(".dzsparallaxer--fadeouttarget").eq(0));b.hasClass("wait-readyall")||setTimeout(function(){z=Number(a.animation_duration)},300);d=b.height();"on"==a.settings_movexaftermouse&&
(n=b.width());"on"==a.cthis_height_is_window_height&&(d=window.innerHeight);l&&(f=l.height(),"on"==a.settings_movexaftermouse&&(G=l.width()));a.settings_substract_from_th&&(f-=a.settings_substract_from_th);U=d;"2"==a.breakout_fix&&console.info(b.prev());b.attr("data-responsive-reference-width")&&(H=Number(b.attr("data-responsive-reference-width")));b.attr("data-responsive-optimal-height")&&(M=Number(b.attr("data-responsive-optimal-height")));0<b.find(".dzsprxseparator--bigcurvedline").length&&b.find(".dzsprxseparator--bigcurvedline").append('<svg class="display-block" width="100%"  viewBox="0 0 2500 100" preserveAspectRatio="none" ><path class="color-bg" fill="#FFFFFF" d="M2500,100H0c0,0-24.414-1.029,0-6.411c112.872-24.882,2648.299-14.37,2522.026-76.495L2500,100z"/></svg>');
    0<b.find(".dzsprxseparator--2triangles").length&&b.find(".dzsprxseparator--2triangles").append('<svg class="display-block" width="100%"  viewBox="0 0 1500 100" preserveAspectRatio="none" ><polygon class="color-bg" fill="#FFFFFF" points="1500,100 0,100 0,0 750,100 1500,0 "/></svg>');0<b.find(".dzsprxseparator--triangle").length&&b.find(".dzsprxseparator--triangle").append('<svg class="display-block" width="100%"  viewBox="0 0 2200 100" preserveAspectRatio="none" ><polyline class="color-bg" fill="#FFFFFF" points="2200,100 0,100 0,0 2200,100 "/></svg>');
    b.get(0)&&(b.get(0).api_set_scrollTop_is_another_element_top=function(a){t=a});0<b.find(".divimage").length||0<b.find("img").length?(m=b.children(".divimage, img").eq(0),m.attr("data-src")?(V=m.attr("data-src"),c(window).bind("scroll",v),v()):E()):E()}function E(){if(!I){I=!0;is_ie11()&&b.addClass("is-ie-11");c(window).bind("resize",ea);ea();b.hasClass("wait-readyall")&&setTimeout(function(){v()},700);setTimeout(function(){b.addClass("dzsprx-readyall");v();b.hasClass("wait-readyall")&&(z=Number(a.animation_duration))},
    1E3);0<b.find("*[data-parallaxanimation]").length&&b.find("*[data-parallaxanimation]").each(function(){var a=c(this);if(a.attr("data-parallaxanimation")){null==C&&(C=[]);C.push(a);var b=a.attr("data-parallaxanimation");try{eval("window.aux_opts2 = "+b)}catch(na){console.info(na),window.aux_opts2=null}if(window.aux_opts2){for(q=0;q<window.aux_opts2.length;q++)0==isNaN(Number(window.aux_opts2[q].initial))&&(window.aux_opts2[q].initial=Number(window.aux_opts2[q].initial)),0==isNaN(Number(window.aux_opts2[q].mid))&&
(window.aux_opts2[q].mid=Number(window.aux_opts2[q].mid)),0==isNaN(Number(window.aux_opts2[q]["final"]))&&(window.aux_opts2[q]["final"]=Number(window.aux_opts2[q]["final"]));a.data("parallax_options",window.aux_opts2)}}});W&&(N=!0,setTimeout(function(){N=!1},W));b.hasClass("simple-parallax")?l.wrap('<div class="simple-parallax-inner"></div>'):O();fa=setInterval(r,1E3);setTimeout(function(){},1500);if(b.hasClass("use-loading")){if(0<b.find(".divimage").length||0<b.children("img").length){if(0<b.find(".divimage").length){V&&
b.find(".divimage").eq(0).css("background-image","url("+V+")");var d=String(b.find(".divimage").eq(0).css("background-image")).split('"')[1];void 0==d&&(d=String(b.find(".divimage").eq(0).css("background-image")).split("url(")[1],d=String(d).split(")")[0]);var e=new Image;e.onload=function(a){b.addClass("loaded")};e.src=d}}else b.addClass("loaded");setTimeout(function(){b.addClass("loaded");ha()},1E4)}b.get(0).api_set_update_func=function(a){D=a};b.get(0).api_handle_scroll=v;b.get(0).api_destroy=
    ma;b.get(0).api_destroy_listeners=oa;"scroll"==a.settings_mode&&(c(window).unbind("scroll",v),c(window).bind("scroll",v),v(),setTimeout(v,1E3),document&&document.addEventListener&&document.addEventListener("touchmove",X,!1));"mouse_body"!=a.settings_mode&&"on"!=a.settings_movexaftermouse||c(document).bind("mousemove",X)}}function ma(){ia=!0;D=null;c(window).unbind("scroll",v);document&&document.addEventListener&&document.removeEventListener("touchmove",X,!1)}function r(){Y=!0}function oa(){clearInterval(fa)}
    function ea(){n=b.width();u=window.innerHeight;Z=window.innerWidth;!1!==I&&(H&&M&&(n<H?b.height(n/H*M):b.height(M)),760>n?b.addClass("under-760"):b.removeClass("under-760"),aa&&clearTimeout(aa),aa=setTimeout(ha,700),"on"==a.js_breakout&&(b.css("width",Z+"px"),b.css("margin-left","0"),0<b.offset().left&&b.css("margin-left","-"+b.offset().left+"px")))}function ha(){d=b.height();f=l.height();u=window.innerHeight;a.settings_substract_from_th&&(f-=a.settings_substract_from_th);if(a.settings_clip_height_is_window_height||
        "on"==a.cthis_height_is_window_height)d=window.innerHeight;0==b.hasClass("allbody")&&0==b.hasClass("do-not-set-js-height")&&0==b.hasClass("dzsparallaxer---window-height")&&0==H&&(f<=U&&0<f?(b.height(f),d=b.height(),is_ie()&&10>=version_ie()?l.css("top","0"):l.css("transform","translate3d(0,0px,0)"),F&&F.css("opacity","0")):b.height(U));l.attr("data-forcewidth_ratio")&&(l.width(Number(l.attr("data-forcewidth_ratio"))*l.height()),l.width()<b.width()&&l.width(b.width()))}function X(b){if("mouse_body"==
        a.settings_mode){g=b.pageY;if(0==f)return;var c=g/u*(d-f);A=g/d;0<c&&(c=0);c<d-f&&(c=d-f);1<A&&(A=1);0>A&&(A=0);P=c}"on"==a.settings_movexaftermouse&&(b=b.pageX/Z*(n-G),0<b&&(b=0),b<n-G&&(b=n-G),ja=b)}function v(h,e){g=c(window).scrollTop();p=0;t&&(g=-parseInt(t.css("top"),10),t.data("targettop")&&(g=-t.data("targettop")));a.settings_listen_to_object_scroll_top&&(g=a.settings_listen_to_object_scroll_top.val);isNaN(g)&&(g=0);h&&"on"==a.init_functional_remove_delay_on_scroll&&(N=!1);var y={force_vi_y:null,
        from:"",force_ch:null,force_th:null,force_th_only_big_diff:!0};e&&(y=c.extend(y,e));a.settings_clip_height_is_window_height&&(d=window.innerHeight);null!=y.force_ch&&(d=y.force_ch);null!=y.force_th&&(y.force_th_only_big_diff?20<Math.abs(y.force_th-f)&&(f=y.force_th):f=y.force_th);!1===I&&(u=window.innerHeight,g+u>=b.offset().top&&E());if(0!=f&&!1!==I&&"scroll"==a.settings_mode){"fromtop"==a.mode_scroll&&(p=g/d*(d-f),"on"==a.is_fullscreen&&(p=g/(f-u)*(d-f),t&&(p=g/(t.height()-u)*(d-f))),"reverse"==
    a.direction&&(p=(1-g/d)*(d-f),"on"==a.is_fullscreen&&(p=(1-g/(f-u))*(d-f),t&&(p=(1-g/(t.height()-u))*(d-f)))));B=b.offset().top;t&&(B=-parseInt(t.css("top"),10));var k=(g-(B-u))/(B+d-(B-u));"on"==a.is_fullscreen&&(k=g/(c("body").height()-u),t&&(k=g/(t.outerHeight()-u)));1<k&&(k=1);0>k&&(k=0);if(C)for(q=0;q<C.length;q++){var v=C[q],m=v.data("parallax_options");if(m)for(var n=0;n<m.length;n++){if(.5>=k){var r=2*k;var w=2*k-1;0>w&&(w=-w);r=w*m[n].initial+r*m[n].mid}else r=2*(k-.5),w=r-1,0>w&&(w=-w),
        r=w*m[n].mid+r*m[n]["final"];w=m[n].value;w=w.replace("{{val}}",r);v.css(m[n].property,w)}}"normal"==a.mode_scroll&&(p=k*(d-f),"reverse"==a.direction&&(p=(1-k)*(d-f)),b.hasClass("debug-target")&&console.info(a.mode_scroll,g,B,u,d,B+d,k));T&&(k=Math.abs((g-B)/b.outerHeight()-1),1<k&&(k=1),0>k&&(k=0),T.css("opacity",k));A=g/d;p=parseInt(p,10);0<p&&(p=0);p<d-f&&(p=d-f);1<A&&(A=1);0>A&&(A=0);y.force_vi_y&&(p=y.force_vi_y);P=p;ka=A;0===z&&(x=P,is_ie()&&10>=version_ie()?l.css("top",""+x+"px"):l.css("transform",
        "translate3d(0,"+x+"px,0)"))}}function O(){if(N)return requestAnimFrame(O),!1;isNaN(x)&&(x=0);Y&&(Y=!1);if(0===z)return D&&D(x),requestAnimFrame(O),!1;J=x;Q=P-J;K=L;R=ka-K;"easeIn"==a.easing&&(x=Number(Math.easeIn(1,J,Q,z).toFixed(5)),L=Number(Math.easeIn(1,K,R,z).toFixed(5)));"easeOutQuad"==a.easing&&(x=Math.easeOutQuad(1,J,Q,z),L=Math.easeOutQuad(1,K,R,z));"easeInOutSine"==a.easing&&(x=Math.easeInOutSine(1,J,Q,z),L=Math.easeInOutSine(1,K,R,z));S=0;"on"==a.settings_movexaftermouse&&(ba=S,la=ja-ba,
        S=Math.easeIn(1,ba,la,z));is_ie()&&10>=version_ie()?l.css("top",""+x+"px"):l.css("transform","translate3d("+S+"px,"+x+"px,0)");F&&F.css("opacity",L);D&&D(x);if(ia)return!1;requestAnimFrame(O)}var b=c(this),l=null,F=null,T=null,q=0,G=0,f=0,d=0,n=G=0,Z=0,u=0,U=0,aa=0,z=0,x=0,S=0,L=0,J=0,ba=0,K=0,P=0,ja=0,ka=0,Q=0,la=0,R=0,D=null,t=null,g=0,p=0,A=0,B=0,V="",I=!1,Y=!1,C=null,ia=!1,N=!1,ca=0,W=0,fa=0,H=0,M=0;ca=Number(a.init_delay);W=Number(a.init_functional_delay);ca?setTimeout(h,ca):h()})};window.dzsprx_init=
    function(a,h){if("undefined"!=typeof h&&"undefined"!=typeof h.init_each&&1==h.init_each){var da=0,E;for(E in h)da++;1==da&&(h=void 0);c(a).each(function(){c(this).dzsparallaxer(h)})}else c(a).dzsparallaxer(h)}})(jQuery);function is_touch_device(){return!!("ontouchstart"in window)}window.requestAnimFrame=function(){return window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||function(c){window.setTimeout(c,1E3/60)}}();
function is_ie(){var c=window.navigator.userAgent,a=c.indexOf("MSIE ");if(0<a)return parseInt(c.substring(a+5,c.indexOf(".",a)),10);if(0<c.indexOf("Trident/"))return a=c.indexOf("rv:"),parseInt(c.substring(a+3,c.indexOf(".",a)),10);a=c.indexOf("Edge/");return 0<a?parseInt(c.substring(a+5,c.indexOf(".",a)),10):!1}function is_ie11(){return!window.ActiveXObject&&"ActiveXObject"in window}function version_ie(){return parseFloat(navigator.appVersion.split("MSIE")[1])}
jQuery(document).ready(function(c){c(".dzsparallaxer---window-height").each(function(){function a(){h.height(window.innerHeight)}var h=c(this);c(window).on("resize",a);a()})});